name: Build RPM

on:
  workflow_dispatch:
  push:
    branches: [ screen-orientation-manager ]
    paths:
      - '**.py'
      - 'meson.build'
      - 'screen-orientation-manager.spec'
      - 'README.md'
      - 'LICENSE'
      - 'rotation-scripts/**'
      - 'known-configs.txt'
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install build dependencies
        run: |
          dnf -y update
          dnf -y install meson python3-devel python3-gobject gtk3-devel xorg-x11-server-utils desktop-file-utils rpm-build git
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up source tarball
        run: |
          VERSION=$(grep Version screen-orientation-manager.spec | awk '{print $2}')
          mkdir -p rpmbuild/SOURCES
          git archive --format=tar.gz --prefix=screen-orientation-manager-$VERSION/ -o rpmbuild/SOURCES/screen-orientation-manager-$VERSION.tar.gz HEAD
      - name: Build RPM
        run: |
          VERSION=$(grep Version screen-orientation-manager.spec | awk '{print $2}')
          rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba screen-orientation-manager.spec
      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpm-artifacts
          path: rpmbuild/RPMS/noarch/*.rpm

      - name: Upload RPM to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: rpmbuild/RPMS/noarch/*.rpm
